port: 7880
rtc:
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: true
  enable_loopback_candidate: true

redis:
  address: 127.0.0.1:6379
  db: 0
  password: "peekle-redis-password"

keys:
  # API Key : Secret Key 
  # These should match the .env variables or application-prod.yml
  livekit_api_key: "peekle_livekit_secret_at_least_32_chars_long"

turn:
  enabled: true
  domain: i14a408.p.ssafy.io
  tls_port: 5349
  udp_port: 3478
  external_tls: true
