port: 7880
logging:
  level: debug
rtc:
  node_ip: 3.39.236.149
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: false
  enable_loopback_candidate: false

redis:
  address: redis:6379
  db: 0
  password: "peekle-redis-password"

keys:
  # API Key : Secret Key 
  # These should match the .env variables or application-prod.yml
  livekit_api_key: "peekle_livekit_secret_at_least_32_chars_long"

turn:
  enabled: true
  domain: i14a408.p.ssafy.io
  cert_file: "/etc/letsencrypt/live/i14a408.p.ssafy.io/fullchain.pem"
  key_file: "/etc/letsencrypt/live/i14a408.p.ssafy.io/privkey.pem"
  tls_port: 5349
  udp_port: 3478
  external_tls: false
  relay_range_start: 30000
  relay_range_end: 30010
