port: 7880
logging:
  level: debug
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50200
  use_external_ip: true
  enable_loopback_candidate: false
  stun_servers:
    - stun.l.google.com:19302
    - stun1.l.google.com:19302
  turn_servers:
    - host: "${METERED_DOMAIN}"
      port: 443
      protocol: tls
      username: "${METERED_USERNAME}"
      credential: "${METERED_PASSWORD}"
    - host: "${METERED_DOMAIN}"
      port: 80
      protocol: tcp
      username: "${METERED_USERNAME}"
      credential: "${METERED_PASSWORD}"

redis:
  address: 127.0.0.1:6379
  db: 0
  password: "peekle-redis-password"

keys:
  # API Key : Secret Key 
  # These should match the .env variables or application-prod.yml
  livekit_api_key: "peekle_livekit_secret_at_least_32_chars_long"

turn:
  enabled: false
  domain: peekle.today
  # cert_file: "/etc/letsencrypt/live/i14a408.p.ssafy.io/fullchain.pem"
  # key_file: "/etc/letsencrypt/live/i14a408.p.ssafy.io/privkey.pem"
  # tls_port: 5349
  udp_port: 3478
  external_tls: false
  relay_range_start: 30000
  relay_range_end: 30200
