services:
  openvidu-server:
    image: openvidu/openvidu-dev:2.32.1
    platform: linux/amd64
    container_name: peekle-openvidu
    restart: unless-stopped
    ports:
      - "8443:8443"
      - "4443:4443"
      - "40000-40050:40000-40050/udp"
      - "40000-40050:40000-40050/tcp"
    env_file:
      - ../.env
    environment:
      - OPENVIDU_SECRET=${OPENVIDU_SECRET:-MY_SECRET}
      - DOMAIN_OR_PUBLIC_IP=localhost
      - OPENVIDU_PUBLICURL=https://localhost/openvidu
      - KMS_MIN_PORT=40000
      - KMS_MAX_PORT=40050
    volumes:
      - openvidu-recordings:/opt/openvidu/recordings
      - openvidu-log:/var/log/openvidu

volumes:
  openvidu-recordings:
  openvidu-log:
