services:
  openvidu-server:
    image: openvidu/openvidu-dev:2.29.0
    container_name: peekle-openvidu
    restart: unless-stopped
    ports:
      - "8443:8443"
      - "4443:4443"
      - "40000-40050:40000-40050/udp"
      - "40000-40050:40000-40050/tcp"
    env_file:
      - .env
    environment:
       - KMS_MIN_PORT=40000
       - KMS_MAX_PORT=40050
    volumes:
      - openvidu-recordings:/opt/openvidu/recordings
      - openvidu-log:/var/log/openvidu

volumes:
  openvidu-recordings:
  openvidu-log:
